"""add the task_done column

Revision ID: 93bd825160dc
Revises: 80fa9bda4572
Create Date: 2025-03-03 15:12:58.892158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bd825160dc'
down_revision: Union[str, None] = '80fa9bda4572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('task_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'task_done')
    # ### end Alembic commands ###
