"""add the student table in database

Revision ID: af92f45bc9d9
Revises: 93bd825160dc
Create Date: 2025-03-03 16:21:43.290628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af92f45bc9d9'
down_revision: Union[str, None] = '93bd825160dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('discription', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('task_done', sa.Boolean(), nullable=True),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Standard', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_Name'), 'student', ['Name'], unique=False)
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=False)
    op.create_index(op.f('ix_student_title'), 'student', ['title'], unique=False)
    op.drop_index('ix_todo_id', table_name='todo')
    op.drop_index('ix_todo_title', table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('task_done', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='todo_pkey')
    )
    op.create_index('ix_todo_title', 'todo', ['title'], unique=False)
    op.create_index('ix_todo_id', 'todo', ['id'], unique=False)
    op.drop_index(op.f('ix_student_title'), table_name='student')
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_index(op.f('ix_student_Name'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
